const { BUILTIN_LEVEL_IDS } = require("../utilities/security/accessLevels")

exports.HOME_SCREEN = {
  description: "",
  url: "",
  props: {
    _id: "d834fea2-1b3e-4320-ab34-f9009f5ecc59",
    _component: "@budibase/standard-components/container",
    _styles: {
      normal: {
        flex: "1 1 auto",
        display: "flex",
        "flex-direction": "column",
        "justify-content": "flex-start",
        "align-items": "stretch",
      },
      hover: {},
      active: {},
      selected: {},
    },
    _code: "",
    className: "",
    onLoad: [],
    type: "div",
    _children: [
      {
        _id: "ef60083f-4a02-4df3-80f3-a0d3d16847e7",
        _component: "@budibase/standard-components/heading",
        _styles: {
          normal: {
            "text-align": "left",
          },
          hover: {},
          active: {},
          selected: {},
        },
        _code: "",
        className: "",
        text: "Welcome to your Budibase App 👋",
        type: "h2",
        _appId: "inst_cf8ace4_69efc0d72e6f443db2d4c902c14d9394",
        _instanceName: "Heading",
        _children: [],
      },
      {
        _id: "cbbf41b27c2b44d1abba38bb694880c6a",
        _component: "@budibase/standard-components/container",
        _styles: {
          normal: {
            display: "flex",
            "flex-direction": "column",
            "justify-content": "center",
            "align-items": "stretch",
            flex: "1 1 auto",
            "border-width": "4px",
            "border-style": "Dashed",
            "margin-bottom": "32px",
          },
          hover: {},
          active: {},
          selected: {},
        },
        _code: "",
        className: "",
        onLoad: [],
        type: "div",
        _appId: "inst_app_2cc_ca3383f896034e9295345c05f7dfca0c",
        _instanceName: "Video Container",
        _children: [
          {
            _id: "c07d752cb3e544b418088fa9be84ba2e4",
            _component: "@budibase/standard-components/embed",
            _styles: {
              normal: {
                width: "100%",
                flex: "1 1 auto",
                opacity: "0",
                "transition-property": "Opacity",
                "transition-duration": "1s",
                "transition-timing-function:": "ease-in",
              },
              hover: {
                "transition-property": "Opacity",
                "transition-duration": "1s",
                "transition-timing-function:": "ease-out",
                opacity: "1",
              },
              active: {},
              selected: {},
            },
            _code: "",
            embed:
              '<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
            _appId: "inst_app_2cc_ca3383f896034e9295345c05f7dfca0c",
            _instanceName: "Rick Astley Video",
            _children: [],
          },
        ],
      },
    ],
    _instanceName: "Home",
  },
  routing: {
    route: "/",
    accessLevelId: BUILTIN_LEVEL_IDS.BASIC,
  },
  name: "d834fea2-1b3e-4320-ab34-f9009f5ecc59",
}

exports.LOGIN_SCREEN = {
  description: "",
  url: "",
  props: {
    _id: "public-master-root",
    _component: "@budibase/standard-components/container",
    _children: [
      {
        _id: "686c252d-dbf2-4e28-9078-414ba4719759",
        _component: "@budibase/standard-components/login",
        _styles: {
          normal: {
            padding: "64px",
            background: "rgba(255, 255, 255, 0.4)",
            "border-radius": "0.5rem",
            "margin-top": "0px",
            margin: "0px",
            "line-height": "1",
            "box-shadow":
              "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
            "font-size": "16px",
            "font-family": "Inter",
            flex: "0 1 auto",
            transform: "0",
          },
          hover: {},
          active: {},
          selected: {},
        },
        _code: "",
        loginRedirect: "",
        usernameLabel: "Username",
        passwordLabel: "Password",
        loginButtonLabel: "Login",
        buttonClass: "",
        _instanceName: "Login",
        inputClass: "",
        _children: [],
        title: "Log in to {{ name }}",
        buttonText: "Log In",
        logo:
          "https://d33wubrfki0l68.cloudfront.net/aac32159d7207b5085e74a7ef67afbb7027786c5/2b1fd/img/logo/bb-emblem.svg",
      },
    ],
    type: "div",
    _styles: {
      active: {},
      hover: {},
      normal: {
        display: "flex",
        "flex-direction": "column",
        "align-items": "center",
        "justify-content": "center",
        "margin-right": "auto",
        "margin-left": "auto",
        "min-height": "100%",
        "background-image":
          "linear-gradient(135deg, rgba(252,215,212,1) 20%, rgba(207,218,255,1) 100%);",
      },
      selected: {},
    },
    _code: "",
    className: "",
    onLoad: [],
  },
  routing: {
    route: "/",
    accessLevelId: BUILTIN_LEVEL_IDS.PUBLIC,
  },
  name: "d834fea2-1b3e-4320-ab34-f9009f5ecc59",
}
